name: Build Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - '1.6.x'

jobs:
  artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java: [ 17 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Upload build results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }} Java ${{ matrix.java }} build results
          path: ${{ github.workspace }}/build/
